### PR TITLE
Reopen PR #19

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Reopen PR #19.

### CODE REVIEW

**Comment by olvlvl** [comment]
GitHub is being stupid :/

**Comment by peter279k** [comment]
> GitHub is being stupid :/

When I fix the conflicts, but I cannot squash the original commit and merged commits to one commit.

Maybe you can consider using this approach to merge PR when I resolve the conflicts.

image

**Comment by olvlvl** [comment]
This is what I see:

image

I'm gonna apply the change a give you credit.

**Comment by peter279k** [comment]
:disappointed:, @olvlvl, that's stupid again.

**Comment by olvlvl** [comment]
You know what? Your changes are actually merged: https://github.com/ICanBoogie/DateTime/blob/master/.travis.yml

**Comment by olvlvl** [comment]
Thanks for your contribution!

**Comment by peter279k** [comment]
I know that, thanks for your effort.

**Pull request closed without merging**
